version: "3.7"

services:
  db:
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentx_database
    volumes:
      - pgdata:/data/postgres
    # networks:
    #   - default

  app:
    build: .
    network_mode: host
    depends_on:
      - db
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    # networks:
    #   - default

volumes:
  pgdata:
    driver: local
